services:
  kos-ko:
    image: kos-ko:latest
    container_name: kos-ko
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - safescan_safescan_net

networks:
  safescan_safescan_net:
    external: true
